services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/restapi_sevice:test-000
    container_name: restapi-service-test
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "1234:1234"
    env_file:
      - ./.env
    networks:
      - my-app
networks:
  my-app:
    name: kafka_network
    external: true