services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/restapi_sevice:test-000
    container_name: restapi-service-test
    restart: always
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
    command: npm run dev
    ports:
      - "1234:1234"

